
GET http://VMSERG:2013/api/token
Accept: application/json
Content-Type: application/x-www-form-urlencoded
{
    "grant_type": "password",
    "username": "admin@sergego.com",
    "password": ""
}

###
GET http://VMSERG:2013/api/jobs

